substitutions:
  name: amysen
  friendly_name: Smart Plug

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  platform: ESP8266
  board: esp01_1m
  project:
    name: amysenplug.esphomeconfig
    version: "1.0"

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:
  manual_ip:
    static_ip: 192.168.20.243
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    
# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

dashboard_import:
  package_import_url: github://stevenjev/amysen/amysenplug-esphome-config.yaml
  import_full_config: false # or true

##### SETTING UP SMART PLUG FUNCTIONS #####
#Device LED Light
light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    id: green_led
    pin: 
      number: GPIO13
      inverted: true

#Device Relay
switch:
  - platform: gpio
    name: ${friendly_name}
    pin: GPIO14
    id: relay
    # Tie LED to relay
    on_turn_on:
    - light.turn_on: green_led
    on_turn_off:
    - light.turn_off: green_led  

#Device Button
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO1
    name: ${friendly_name} Power Button
    on_press:
      - switch.toggle: relay
    internal: true
